### PR TITLE
Avoiding conditional directives that break statements.

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by RomeroMalaquias** [comment]
Hello?

**Comment by jasone** [comment]
I have a nontrivial backlog of issues to work through over the coming weeks, which is why I hadn't yet responded.  This particular pull request does not provide a rationale on which to be judged, which means I have no way to know whether it should be treated as anything more than stylistic criticism.

**Comment by RomeroMalaquias** [comment]
Ok, thanks

**Comment by RomeroMalaquias** [comment]
I will wait

**Comment by jasone** [comment]
There is still no stated justification for this change, and stylistic preference alone is insufficient.  Closing.

**Pull request closed without merging**
