### PR TITLE
Fix chunk_alloc_dss() regression.

### PR DESCRIPTION
**Pull request by jasone**
Fix chunk_alloc_dss() to account for bytes that are not a multiple of
the chunk size.  This regression was introduced by
e2bcf037d445a84a71c7997670819ebd0a893b4a (Make dss operations
lockless.), which was first released in 4.3.0.

### CODE REVIEW

**Comment by jasone** [comment]
Well, that's discouraging, because it's unrelated to this diff, and I can't reproduce it locally.

**Comment by jasone** [comment]
It's likely that the test failure is due to incorrect OOM handling somewhere.  I'm going to have to test in a RAM-constrained environment.  Meanwhile, I don't think that should block this diff.

**Comment by davidtgoldblatt** [comment]
Note that you can kick off a rebuild by clicking through on the "Details" link and clicking "Rebuild". I started one for the failing ubuntu build.

**Comment by jasone** [comment]
I have an intermittent repro (and a core file) on a RAM-constrained Ubuntu VM.  It may be hard to diagnose without a more reliable failure, but this is a start at least.

**Comment by jasone** [comment]
I investigated enough to verify that the test failure is not specific to this change, and created #647 to track fixing the issue.

**Pull request merged**
