### PR TITLE
[Testing] Travis CI fix

### PR DESCRIPTION
**Pull request by interwq**

### CODE REVIEW

**Comment by interwq** [comment]
@davidtgoldblatt : the current hacky change seems working https://travis-ci.org/jemalloc/jemalloc/jobs/274747194.

If you are not against avoiding the mutex in the oom handler, I'll do a spin lock there.

**Comment by davidtgoldblatt** [comment]
Why not just use a malloc_mutex_t? We've managed to purge almost all spinlock-esque constructs elsewhere; I'm hesitant to let that number increase.

**Comment by interwq** [comment]
Static initialization for the mutex could be a bit tricky. But should work. Let me try that.

**Comment by davidtgoldblatt** [comment]
I think we can just do static malloc_mutex_t mtx = MALLOC_MUTEX_INITIALIZER, no?

**Comment by interwq** [comment]
IIRC we'll need to do some dance for Windows like this one: https://github.com/jemalloc/jemalloc/blob/e55c3ca26758bcb7f6f1621fd690caa245f16942/src/jemalloc.c#L128-L131

It looks MALLOC_MUTEX_INITIALIZER wasn't doing anything for Windows: https://github.com/jemalloc/jemalloc/blob/18ecbfa89e7dd39a802f52bcd461184b8065e97e/include/jemalloc/internal/mutex.h#L101

**Comment by interwq** [comment]
Well I guess I can stop trying the mutex thing since this one fails: https://travis-ci.org/jemalloc/jemalloc/jobs/274747211

**Comment by interwq** [comment]
@davidtgoldblatt: I guess the tricks here are done. Do you mind taking it over with enforcing the platform version? I haven't looked at that part much.

**Comment by davidtgoldblatt** [comment]
Can do.

**Pull request closed without merging**
