### PR TITLE
Automatically mangle private symbols

### PR DESCRIPTION
**Pull request by jasone**

### CODE REVIEW

**Comment by jasone** [comment]
So much fail. :disappointed:

**Comment by jasone** [comment]
No more fail!  Ready for review.

**Comment by jasone** [comment]
Mmm, awk.  I experienced a strange delight while learning and using a rather ancient language which inspired others I have used for *decades*.

**Comment by tamird** [comment]
Unfortunately the way "nm" is hardcoded here means that this breaks under cross compilation.

**Comment by jasone** [comment]
@tamird, how can we fix it?  Add an overrideable configure variable?

**Comment by tamird** [comment]
@benesch and I are working on a fix - we'll send a PR.

**Pull request merged**
