### PR TITLE
Fixup auxcount when a contradiction is detected.

### PR DESCRIPTION
**Pull request by deadalnix**
That seems like a sensible thing to try, but please benchmark and let me know.

### CODE REVIEW

**Comment by guangli-dai** [comment]
Tested it on a heavy workload, CPU cycles actually suffer from a small regress (<1%) and no wins are observed. Unfortunately, the CPU sampling tooling is not working fine and I cannot provide more details regarding why from the experiments.

**Comment by deadalnix** [comment]
I wasn't too sure about this one, but lacked a way to measure it precisely. I still think there is something there. Let's try something simpler.

**Comment by guangli-dai** [comment]
The new version performs slightly better, but still neutral to small regression (~ 0.5%) across various contention-heavy workloads.

**Comment by deadalnix** [comment]
Ok, let's just close this, then?

**Pull request closed without merging**
