### PR TITLE
Add Cirrus-CI config for FreeBSD builds

### PR DESCRIPTION
**Pull request by jasone**
This configures Cirrus CI's test runner (original at https://github.com/lwhsu/jemalloc/commit/e10935ffd2047eb1e23c13a1586990dcfc6ad9f0) to test on FreeBSD.  I've already enabled Cirrus CI on  https://github.com/jemalloc/jemalloc, so this pull request should trigger test runs.

### CODE REVIEW

**Comment by jasone** [comment]
The only odd thing I see is that the jemalloc source appears not to be a full git clone, which results in
```
jemalloc version   : 0.0.0-0-g0000000000000000000000000000000000000000
```
It's not clear to me how the source even ends up in the Cirrus CI container, and I haven't found any related documentation.

**Comment by jasone** [comment]
Trying @interwq's suggestion.

**Comment by interwq** [comment]
Looks to be failing with 
‘
git clone --tags --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
Cloning into '/tmp/cirrus-ci-build'...
fatal: Remote branch pull/1404 not found in upstream origin

Exit status: 128
‘

**Comment by jasone** [comment]
Dang, this still isn't right.  Unfortunately, the logs for the first (successful) run aren't verbose enough by default to show the git commands that actually succeed with the built-in git, and the environment variable expansions aren't shown either.  I'm going to add an `echo_script` to improve visibility.

**Pull request merged**
