### PR TITLE
Make high resolution timer default for profiling

### PR DESCRIPTION
**Pull request by yinan1048576**

### CODE REVIEW

**Comment by davidtgoldblatt** [comment]
Is this correct? I don't know about the high-res timer guarantees on all the platforms we support (maybe POSIX guarantees realtime clocks too)?

**Comment by yinan1048576** [comment]
I haven't looked into the code. Won't it fall back to the default timer?

**Comment by davidtgoldblatt** [comment]
I think as a question of accuracy; CLOCK_REALTIME can go backwards, while CLOCK_MONOTONIC can't (I think?). So we can incorrectly (rather than just coarsely) report allocation lifetimes with this change.

**Comment by yinan1048576** [comment]
Got it. Then let's leave the default timer as default.

> So we can incorrectly (rather than just coarsely) report allocation lifetimes with this change.

nit: the time should be of higher resolution rather than being coarse with this change?

**Pull request closed without merging**
