### PR TITLE
install: do not use "install -v", it's not portable

### PR DESCRIPTION
**Pull request by 0-wiz-0**
At least NetBSD's install(1) does not support this.

### CODE REVIEW

**Comment by Lapenkov** [comment]
What a pity! It's way nicer than to echo every command. But let's resort to what we had before to still keep it verbose:
https://github.com/jemalloc/jemalloc/commit/f15d8f3b416f6812ac030bc1a7aacf05927a4d7f

**Comment by 0-wiz-0** [comment]
Thanks for comment, @Lapenkov.
Yes, a pity indeed.
Should I change my pull request or will you just revert your commit?

**Comment by Lapenkov** [comment]
> Thanks for comment, @Lapenkov. Yes, a pity indeed. Should I change my pull request or will you just revert your commit?

Right, I just reverted my commit: https://github.com/jemalloc/jemalloc/commit/df7ad8a9b6121c5c4b15bad5606b51bf734416a6

Thank you for bringing this up!

**Comment by BusyJay** [comment]
Hi, can we get a release for this?

**Pull request closed without merging**
