### PR TITLE
Fallback to unbuffered printing if OOM

### PR DESCRIPTION
**Pull request by yinan1048576**
Also added stronger assertions in the buffered writer initializer.

### CODE REVIEW

**Comment by interwq** [comment]
LGTM. However I do wonder if we should make the effort to tolerate OOM (vs simply report failure).

@davidtgoldblatt opinions? If you are not against the change, we should find a way to test the OOM paths (minimal we can do is probably, define the PRINT_BUFSIZE to be huge to trigger OOM, and run CI in that case).

**Comment by yinan1048576** [comment]
> However I do wonder if we should make the effort to tolerate OOM (vs simply report failure).

Right, I also was not totally sure. The reason why I chose not to report a failure is that we may not always have a good way to do so. For example, `malloc_stats_print()` doesn't have a way to return error.

> we should find a way to test the OOM paths

Agree. And in general we should have a way to test the OOM paths for a lot of other places in the code base. I think we could mock our internal allocator (using the technique of function pointer).

**Comment by davidtgoldblatt** [comment]
Sorry, I missed this diff in my inbox. This seems reasonable to me. I agree about oom testing, as well.

**Comment by yinan1048576** [comment]
Rebase and Tested the OOM case by manually set the buffer pointers to NULL. No build/test failures. (Unit tests contain calls to all three buffered writer usages.)

Testing OOM more generally doesn't seem trivial. Will need to think more at a later time.

**Pull request merged**
