### PR TITLE
making prof_active flag atomic and removing its corresponding mutex

### PR DESCRIPTION
**Pull request by rkmisra**
Made prof_active flag atomic to address #1162

### CODE REVIEW

**Comment by gnzlbg** [comment]
@davidtgoldblatt do you have links to the bug report?

**Comment by davidtgoldblatt** [comment]
I didn't file one upstream; I just threw it at a couple compiler people I know.

I dug around the llvm source a little the last time around, and it seems like it should be an easy fix by introducing an acquire_cmp primitive (analogous to the acquire_mov it currently uses to prevent reordering). The "generate a cmp here" and "generate an acquire_mov" logic is already in the same pass. Then again I'm not really a compiler person so maybe this is hard for some reason I don't know about.

**Comment by gnzlbg** [comment]
There is one now: https://bugs.llvm.org/show_bug.cgi?id=38405 We'll see what happens.

**Comment by davidtgoldblatt** [comment]
Missed optimization opportunity still exists -- if it gets fixed, we can fix this. For now, clearing out old PRs.

**Pull request closed without merging**
