### PR TITLE
Suppress verbose frame address warnings

### PR DESCRIPTION
**Pull request by Svetlitski**
These warnings are not useful, and make the output of some CI jobs [enormous and difficult to read](https://api.cirrus-ci.com/v1/task/6489320555544576/logs/main.log), so let's suppress them.

### CODE REVIEW

**Review by interwq — APPROVED** [review]
LGTM! The PR is marked as draft -- Should I merge now or you plan to change anything?

**Comment by Svetlitski** [comment]
> LGTM! The PR is marked as draft -- Should I merge now or you plan to change anything?

All good now, just needed to double-check something earlier.

**Comment by interwq** [comment]
I'm getting "This branch cannot be rebased due to too many changes" and not allowed to merge. No idea what triggered this since Kevin's branch is already based on current dev. @Svetlitski maybe try force push again and see if it resolves itself?

**Comment by Svetlitski** [comment]
@interwq It's still showing "This branch cannot be rebased due to too many changes" even after force-pushing again. I'm going to try creating a new PR with identical contents to see if that works.

**Comment by Svetlitski** [comment]
Nope, that didn't work either (#2488)

**Comment by interwq** [comment]
First time seeing this. One quick thing to try, maybe try removing the commit msg (wondering if the markdown there triggered a bug).

**Comment by Svetlitski** [comment]
Even after rebasing again following #2482 being merged, the issue still hasn't gone away.

**Pull request merged**
