### PR TITLE
dev: make symbol listing work when cross-compiling

### LINKED ISSUE #950: Port #949 to dev
I didn't realize this when I merged, but #949 was applied to master only. We should forward-port it to dev.

### PR DESCRIPTION
**Pull request by tamird**
Port of #949. Closes #950.

### CODE REVIEW

**Comment by tamird** [comment]
Test failures seem unrelated. @jasone care to have a look?

**Comment by tamird** [comment]
or perhaps @davidtgoldblatt

**Comment by davidtgoldblatt** [comment]
I'm like 99% sure it's unrelated, and fixed by 99b91f8b3d5b2ecac854959d6f9c0b2fcfa01753 (which I just merged in). Would you mind rebasing past it just to be on the safe side?

**Comment by tamird** [comment]
Done.

**Comment by davidtgoldblatt** [comment]
Thanks for the fixes, and for the forward-porting.

**Pull request merged**
