### PR TITLE
optimize calculation of next power of 2 >= of given number

### PR DESCRIPTION
**Pull request by rkmisra**
This overrides #1118 and is being used to push changes required to implement #674 
This is being done for clean commit and merge.

### CODE REVIEW

**Comment by gnzlbg** [comment]
LGTM. @davidtgoldblatt this should be good to go.

**Comment by davidtgoldblatt** [comment]
Nit: could you clean up the commit message a little? E.g. "Bit_util: Use intrinsics for pow2_ceil, where available."

**Comment by rkmisra** [comment]
Is current commit message good enough or should I add more details?

**Comment by davidtgoldblatt** [comment]
Looks great, thanks!

**Pull request merged**
