### PR TITLE
Fresh PR for PPC64LE

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

I have made changes to gen_travis.py and got different options with gcc enabled for PPC64LE as well, request you to please review.

Thanks 

Old PR can be purged #1912

### CODE REVIEW

**Comment by davidtgoldblatt** [comment]
Looks good, two procedural nits:
 - Could you squash these down into one commit? We disable squash-and-merge to avoid doing it accidentally for big PRs.
- Could you retitle the commit to "CI support for PPC64LE architecture" (just to disambiguate with a code fix).

**Comment by davidtgoldblatt** [comment]
(And, thanks for doing this, it's quite useful).

**Comment by ezeeyahoo** [comment]
You are welcome David
I hae addressed those nits. Please review.

**Comment by davidtgoldblatt** [comment]
Looks good, thank you!

**Pull request merged**
