### PR TITLE
Silence harmless warnings discovered via run_tests.sh.

### PR DESCRIPTION
**Pull request by jasone**

### CODE REVIEW

**Comment by jasone** [comment]
Huh, all the macOS CI jobs were cancelled.  Infra failure?  I don't see any way to dig into what happened.

**Comment by jasone** [comment]
Ah yes, https://www.traviscistatus.com/ says infra failure.

**Comment by davidtgoldblatt** [comment]
Yeah. If you sign in to travis, they'll send you emails about it. Link: https://www.traviscistatus.com/incidents/k79mjcv403c4

**Comment by jasone** [comment]
Manually tested on macOS; pushing.

**Pull request merged**
