### PR TITLE
Extract a page allocation ("pa") module

### PR DESCRIPTION
**Pull request by davidtgoldblatt**
This (extremely long -- I'm sorry Yinan!) PR gathers together all the assorted page-level accessors, stats, and functionality, and consolidates it into one place.

We along the way pull out and test various bits of helper functionality (like decay), which previously only got touched by integration tests. We also simplify much of the stats code, and split up the page-level stats from the allocation-level ones.

This is a fairly nice cleanup on its own (compare e.g. the slab and large alloc pathways before and after this change, and their similarity). But the real benefit comes in just having the pa module interface itself. We can now have a place to interpose arbitrary alternate allocation strategies; it enables the hugepage-backed page allocator coming in a later PR. It's even testable in isolation. (Even in a program that calls malloc! You can spin up an entirely separate base and emap for testing).

Unfortunately, some of the details of that later PR snuck into this one in ways that are sort of hard to rebase out of (like the "ranged" bit added to the edata). They aren't terribly well-motivated at the moment, but I promise they're useful down the road.

This gets a big chunk of the way towards de-arenafication. The pa shard an arena contains is logically separate from it; there's no reason that, in the future, the arena->shard mapping can be dynamic (say, with multiple auto arenas sharing a single pa_shard, while manual arenas get their own).

This is not as complete as it could be. I think a future world has the page allocator know even less about how the extents it returns get used (i.e. the values of slab and szind are the business of the arena and emap, not the page allocator), but this PR is sprawling enough as it is.

### CODE REVIEW

**Comment by yinan1048576** [comment]
Will review next week.

**Comment by davidtgoldblatt** [comment]
> Out of curiosity, I haven't looked all the way into the decay module, but is there anything e.g. a paper that explains why we should use the smoothstep model for decaying?

This was a little bit before my time, so I couldn't say for sure the motivations there. Two things I'd suggest are https://github.com/jemalloc/jemalloc/issues/325 and https://www.youtube.com/watch?v=RcWp5vwGlYU , which give the motivation for time-based decay generally but not smoothstep specifically. I think it's mostly an engineering decision overall; i.e. there's not some subtle mathematical justification for smooth-step over ratio-based decay or something else entirely. Over the years we've talked about alternative or mixed strategies.

> A minor comment regarding forking handling: it feels to me that we can have a perhaps centralized module for that. I'm having trouble trying to always remember to handle each new mutex. (This doesn't need to be part of this PR.)

Indeed -- see https://github.com/jemalloc/jemalloc/issues/943 . There was a PR for this a while back, but we failed to follow up (unfortunately. I still think it's a good idea): https://github.com/jemalloc/jemalloc/pull/1153 .

> I'm a bit lost while reading your last stage of commits where the rtree is involved (starting from 70de0cd). Can you explain on a high level the set of goals you're trying to achieve?

I'm sorry; these are a little bit jumbled (some rebases got a little bit messy here). I think there are a few buckets:
- The rtree changes are just simplifications of metadata management to make that code easier to wrangle, in the service of later changes to come.
- The emap changes make it stop modify the edata_t itself. This moves the emap more towards its goal of only handling mapping, rather than some combination of mapping and edata management.
- The extent changes are similar. The extent/pa modules should only concern themselves with page-level allocation; the way that the caller is going to use the returned value shouldn't matter to them.
- The parameterization changes are purely in the service of improving testability.
- Pulling emap_global out of emap does likewise. After this change, we can test the page-level allocator on its own, without touching the same emap that the test program uses. (I don't actually have such a test in this PR, but I've got one written).

The addition of the edata ranged bit is for an incoming hugepages PR. The history here is that I wrote it first, did some of the other refactorings in that PR, and then realized that they ought to go in this one. But that means that all the refactorings that touch edatas assume that it has a ranged-bit initializer, and pulling it out only to put it back in in the next PR seemed like a pain.

**Comment by yinan1048576** [comment]
Thank you for the pointers. I think I know better now why we need a sigmoidal curve. I'll think more about the fork handling module.

I'll look at the last section on Friday. Meanwhile, I forgot another nit: I liked that you extracted out the lockedstat module, and I think there should be a way to further unify it with the counter module (see https://github.com/jemalloc/jemalloc/commit/d71a145ec1bb8153c3d69be27eea5b076d59abfe). The counter module has the same `#ifdef JEMALLOC_ATOMIC_U64` business, only except that it assumes a built-in mutex and it has a fancier pair of add/subtract. Possible consolidation can be done in a later PR, but for now, it seems the name "locked stat" is not general enough to include scenarios like the prof / stat dumping "stopwatch". Perhaps "locked counter" or something?

**Comment by davidtgoldblatt** [comment]
What about just naming the module `lockedint`, and the functions/types `locked_u64_t` and `locked_zu_t`?

**Comment by davidtgoldblatt** [comment]
(Just because "counter" is a little wordy).

**Comment by yinan1048576** [comment]
Yes, sounds good.

**Comment by davidtgoldblatt** [comment]
^--- lockedstat renaming

**Comment by davidtgoldblatt** [comment]
Oh absolutely (in fact, I think one of the nice features of this PR is that it allows that testing without going through all the machinery in between realloc and extent.c).

**Pull request merged**
