### PR TITLE
Fix warnings 

### PR DESCRIPTION
**Pull request by interwq**
Fix warnings discovered in #1019.

### CODE REVIEW

**Comment by davidtgoldblatt** [comment]
Does the fallthrough thing actually fix the fallthrough warnings? I thought you needed a special attribute.

(We should still probably leave #1019 open after this though, there's a couple other things it found).

**Comment by interwq** [comment]
Comments can also be used mentioned here: https://gcc.gnu.org/gcc-7/changes.html

Also since we have many other places using fall through comments not reported, so I assumed this fixed it.

**Comment by interwq** [comment]
Yeah the left shift by negative thing has been fixed yet.

**Comment by davidtgoldblatt** [comment]
Huh, legit-seeming travis failures?

https://travis-ci.org/jemalloc/jemalloc/jobs/277047620

**Comment by interwq** [comment]
Tried for a while but couldn't repro or relate to the changes here... I'll drop the rtree initializer diff for now and retry.

**Comment by interwq** [comment]
@davidtgoldblatt : these 2 diffs work fine. Let's land them and I'll try other fixes on top?

**Pull request merged**
