### PR TITLE
Add support for QNX.

### PR DESCRIPTION
**Pull request by jqian82**
pthread_key_create on QNX triggers recursive allocation during tsd
bootstrapping. Using tsd_init_check_recursion to detect that.

Before pthread_key_create, the address of tsd_boot_wrapper is returned
from tsd_get_wrapper instead of using TLS to store the pointer.
tsd_set_wrapper becomes a no-op. After that, the address of
tsd_boot_wrapper is written to TLS and bootstrap continues as before.

### CODE REVIEW

**Comment by davidtgoldblatt** [comment]
BTW, not ignoring this -- trying to figure out why CI isn't triggering correctly.

In general, I'm not opposed to merging these kinds of fixes, but at the same time, I want to sort of warn that since we don't test on QNX or even have easy access to it, weird bugs, breakages, etc. will sneak in from time to time.

**Comment by jqian82** [comment]
Hi David, I remember seeing error like "account too new for using farm resource". Not sure if that's related with the failure. If you haven't looked at the diff yet, I'm going to close this one and upload with my company account if that works for you?

**Comment by davidtgoldblatt** [comment]
Sure, no problem at all.

**Comment by jqian-aurora** [comment]
> Sure, no problem at all.

Hi David, a new pull request was uploaded here under my company email account.
https://github.com/jemalloc/jemalloc/pull/1972

It received the same failure though. Not sure if there's anything I can do. Please let me know. I'm happy to move it forward.
"User is too new to use Community clusters! Please check with support!"

Thanks!
Jin

**Comment by hbwang15** [comment]
> Hi David, I remember seeing error like "account too new for using farm resource". Not sure if that's related with the failure. If you haven't looked at the diff yet, I'm going to close this one and upload with my company account if that works for you?

> Awesome! Thank you, David!
I Use your fork branch to build success. but run on qnx, coredump happend. here is the backtrace.

> #0  atomic_store_p (mo=atomic_memory_order_release, val=0xe800001020a700, a=0x806e8) at include/jemalloc/internal/atomic.h:83
83	JEMALLOC_GENERATE_ATOMICS(void *, p, LG_SIZEOF_PTR)
(gdb) bt
#0  atomic_store_p (mo=atomic_memory_order_release, val=0xe800001020a700, a=0x806e8) at include/jemalloc/internal/atomic.h:83
#1  rtree_leaf_elm_write (tsdn=0x78099000 <opt_node+1232>, rtree=<optimized out>, elm=0x806e8, contents=...) at include/jemalloc/internal/rtree.h:247
#2  emap_rtree_write_acquired (tsdn=0x78099000 <opt_node+1232>, emap=<optimized out>, slab=false, szind=232, edata=0x1020a700, elm_b=0x806e8, elm_a=0x806e8) at src/emap.c:144
#3  je_emap_register_boundary (tsdn=tsdn@entry=0x7809a2f0 <je_tsd_boot_wrapper+8>, emap=<optimized out>, edata=edata@entry=0x1020a700, szind=szind@entry=232, slab=slab@entry=false) at src/emap.c:161
#4  0x0000000078049b10 in extent_register_impl (pac=0x102032a0, gdump_add=true, edata=0x1020a700, tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>) at src/extent.c:293
#5  extent_register (edata=0x1020a700, pac=0x102032a0, tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>) at src/extent.c:310
#6  je_extent_alloc_wrapper (tsdn=tsdn@entry=0x7809a2f0 <je_tsd_boot_wrapper+8>, pac=pac@entry=0x102032a0, ehooks=ehooks@entry=0x102000c0, new_addr=new_addr@entry=0x0, size=size@entry=4096, 
    alignment=alignment@entry=4096, zero=false, zero@entry=32, commit=commit@entry=0x100b8975) at src/extent.c:795
#7  0x000000007804a944 in je_ecache_alloc_grow (tsdn=tsdn@entry=0x7809a2f0 <je_tsd_boot_wrapper+8>, pac=pac@entry=0x102032a0, ehooks=ehooks@entry=0x102000c0, ecache=ecache@entry=0x10205970, 
    new_addr=new_addr@entry=0x0, size=size@entry=4096, alignment=alignment@entry=4096, zero=zero@entry=false) at src/extent.c:114
#8  0x0000000078055260 in pac_alloc_impl (tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>, self=0x102032a0, size=4096, alignment=4096, zero=<optimized out>) at src/pac.c:117
#9  0x0000000078053c40 in pai_alloc (zero=false, alignment=4096, size=4096, self=0x102032a0, tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>) at include/jemalloc/internal/pai.h:25
#10 je_pa_alloc (tsdn=tsdn@entry=0x7809a2f0 <je_tsd_boot_wrapper+8>, shard=0x10203290, shard@entry=0x2, size=4096, alignment=alignment@entry=4096, slab=slab@entry=true, szind=szind@entry=1, 
    zero=zero@entry=false) at src/pa.c:114
#11 0x000000007801ba88 in arena_slab_alloc (bin_info=<optimized out>, binshard=<optimized out>, binind=1, arena=0x10200940, tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>) at src/arena.c:684
#12 arena_malloc_small (zero=false, binind=1, arena=0x10200940, tsdn=0x7809a2f0 <je_tsd_boot_wrapper+8>) at src/arena.c:995
#13 je_arena_malloc_hard (tsdn=tsdn@entry=0x7809a2f0 <je_tsd_boot_wrapper+8>, arena=0x10200940, size=size@entry=16, ind=ind@entry=1, zero=zero@entry=false) at src/arena.c:1043
#14 0x000000007800e80c in arena_malloc (slow_path=<optimized out>, tcache=<optimized out>, zero=<optimized out>, ind=<optimized out>, size=<optimized out>, arena=<optimized out>, tsdn=<optimized out>)
    at include/jemalloc/internal/arena_inlines_b.h:156
#15 iallocztm (slow_path=<optimized out>, arena=<optimized out>, is_internal=<optimized out>, tcache=<optimized out>, zero=<optimized out>, ind=<optimized out>, size=<optimized out>, 
    tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#16 imalloc_no_sample (ind=<optimized out>, usize=<optimized out>, size=<optimized out>, tsd=<optimized out>, dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2290
#17 imalloc_body (tsd=0x7809a2f0 <je_tsd_boot_wrapper+8>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2465
#18 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2586
#19 je_malloc_default (size=16) at src/jemalloc.c:2614
#20 0x0000000001030ca8 in ?? ()
#21 0x000000007809a2f0 in je_tsd_boot_wrapper () from /root/jemalloc/lib/libjemalloc.so.2


do you have some any configure option when build jemalloc for qnx? 谢谢

**Pull request closed without merging**
