### PR TITLE
Some cleanups for source files

### PR DESCRIPTION
**Pull request by yinan1048576**
This is an answer to https://github.com/jemalloc/jemalloc/pull/1794#discussion_r438383165. It goes beyond #1794 so separate it out.

### CODE REVIEW

**Comment by davidtgoldblatt** [comment]
And, just to double-check: after this diff, there's nothing that matches `JEMALLOC_.*_C_`, right?

**Comment by yinan1048576** [comment]
Right. What I did was exactly the `sed` command I put into the commit summary.

**Comment by davidtgoldblatt** [comment]
Right, but what I mean is, we want to make sure that there's no `#ifdef ARENA_C_` or anything left (which the ifdef thing wouldn't catch). Checked though, looks OK.

**Comment by davidtgoldblatt** [comment]
I think we can also remove hash.c, prng.c, and ticker.c.

**Comment by yinan1048576** [comment]
> Right, but what I mean is, we want to make sure that there's no `#ifdef ARENA_C_` or anything left (which the ifdef thing wouldn't catch). Checked though, looks OK.

That's great point. Also checked, and as you mentioned, there isn't anything like that.

> I think we can also remove hash.c, prng.c, and ticker.c.

Makes sense. Added a commit.

**Pull request merged**
