### PR TITLE
Update and rename INSTALL to INSTALL.md

### PR DESCRIPTION
**Pull request by KindDragon**
[Render](https://github.com/KindDragon/jemalloc/blob/623233a68f321daeb73d2b3977cea652d682fb9e/INSTALL.md)

### CODE REVIEW

**Comment by jasone** [comment]
Please squash the two commits so I can "rebase and merge"; there's no "squash, rebase, and merge" option in the GitHub GUI.

**Comment by KindDragon** [comment]
Squash option will create new commit on top `dev` branch, so it's like "rebase and squash"

**Comment by davidtgoldblatt** [comment]
We try to keep clean commit histories; that leaves 1 commit in the history as opposed to an original + a fixup.

**Comment by KindDragon** [comment]
GitHub squash can do this for you

**Comment by jasone** [comment]
Thanks!

**Pull request merged**
