### PR TITLE
Test on more FreeBSD versions

### PR DESCRIPTION
**Pull request by mchoo7**
https://github.com/jemalloc/jemalloc/pull/2228 should be landed first and then this pull request.

Problems that block https://github.com/jemalloc/jemalloc/pull/2228 is solved, and I modified a line to use 13.2-RELEASE

### CODE REVIEW

**Comment by interwq** [comment]
@fel1x-developer it looks 12.3 and 13.2 are failing the profiling enabled builds with:

> error: unknown warning group '-Wframe-address'

Probably because of older compilers missing the feature? It's used to suppress warnings here:
https://github.com/jemalloc/jemalloc/blob/e4817c8d89a2a413e835c4adeab5c5c4412f9235/src/prof_sys.c#L103

**Comment by mchoo7** [comment]
If this fails, we can manually install `llvm` from `pkg`.

**Comment by mchoo7** [comment]
[FreeBSD phabricator revision](https://reviews.freebsd.org/D41421)

[This bug in 13.2-RELEASE](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273085) is blocking CI. This will be fixed in 13.3-RELEASE which will be released in the spring of 2024. I will disable test for 13.2-RELEASE and use 13.0 for now.

**Comment by fel1x-developer** [comment]
If needed, I can add `13-STABLE` and `14-STABLE` CIs.

**Comment by interwq** [comment]
Thanks again @fel1x-developer ! CI looks clean -- is #2228 still needed? It looks this one covers that already? If so I'll merge here and close that one.

**Comment by mchoo7** [comment]
> Thanks again @fel1x-developer ! CI looks clean -- is #2228 still needed? It looks this one covers that already? If so I'll merge here and close that one.

#2228 is not needed anymore. It can be closed after merge.

**Comment by interwq** [comment]
@fel1x-developer FYI that we also have FreeBSD through TravisCI:
https://github.com/jemalloc/jemalloc/blob/dev/scripts/gen_travis.py#L10

which generates:
https://github.com/jemalloc/jemalloc/blob/dev/.travis.yml#L37

We will keep both Travis and Cirrus at least in the short term. The travis FreeBSD builds (which appears to be FreeBSD 12?) look broken right now:
https://app.travis-ci.com/github/jemalloc/jemalloc/jobs/615835615

**Comment by devnexen** [comment]
Note that FreeBSD 12 is EOL now.

**Comment by mchoo7** [comment]
> @fel1x-developer FYI that we also have FreeBSD through TravisCI: https://github.com/jemalloc/jemalloc/blob/dev/scripts/gen_travis.py#L10
> 
> which generates: https://github.com/jemalloc/jemalloc/blob/dev/.travis.yml#L37
> 
> We will keep both Travis and Cirrus at least in the short term. The travis FreeBSD builds (which appears to be FreeBSD 12?) look broken right now: https://app.travis-ci.com/github/jemalloc/jemalloc/jobs/615835615

FreeBSD CI on Travis should be removed since it [only provides FreeBSD 12.1](https://docs.travis-ci.com/user/reference/freebsd/#using-freebsd), which became EOL on January 31st, 2021.

**Comment by interwq** [comment]
Thanks @devnexen @fel1x-developer. I'll contact Travis CI and see if they will upgrade to a recent version.

Removing the tests on Travis for now #2589.

**Pull request merged**
